version: "3.8"

services:
  clamav-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AV_API_KEY=${AV_API_KEY:-supersecretkey123}
    volumes:
      - clamav_db:/var/lib/clamav
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  clamav_db:
    driver: local
