# Semgrep rules for this project
rules:
  - id: no-eval
    message: Avoid eval, it can lead to code injection vulnerabilities.
    severity: ERROR
    languages: [javascript, typescript]
    pattern: eval(...)

  - id: insecure-http-fetch
    message: Use HTTPS for network requests.
    severity: WARNING
    languages: [javascript, typescript]
    pattern-regex: "fetch\\(\\s*['\"]http://"

  - id: no-inner-html-assign
    message: Avoid assigning to innerHTML directly.
    severity: WARNING
    languages: [javascript, typescript]
    pattern-regex: "\.innerHTML\\s*="