[build]
command = "npm run db:push -- --accept-data-loss && npm run db:seed && npm run build"
publish = ".next"

[build.environment]
DATABASE_URL = "${NETLIFY_DATABASE_URL}"
# Increase npm network resiliency on Netlify
NPM_CONFIG_FETCH_RETRIES = "5"
NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "120000"
NPM_CONFIG_NETWORK_TIMEOUT = "600000"
NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_PROGRESS = "false"

# Enable Netlify's official Next.js runtime to serve App Router/SSR/API routes
[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-lighthouse"
