[build]
  command = "pnpm db:generate && if [ -n \"$NETLIFY_DATABASE_URL\" ]; then pnpm db:migrate && pnpm db:seed; else echo 'Skipping Prisma migrate/seed (NETLIFY_DATABASE_URL not set)'; fi && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "UPLOADS_PROVIDER,REALTIME_TRANSPORT"

[dev]
  command = "pnpm dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
