# Netlify configuration for Accounting Firm (Next.js 15.5.2 with Turbopack)
# NOTE: Do not commit secrets. Set DATABASE_URL, NEXTAUTH_SECRET and NEXTAUTH_URL in the Netlify site settings (Environment) UI.

[build]
  command = "npm run build"
  publish = ".next"
  environment = { 
    NODE_VERSION = "18.20.0",
    NEXT_TELEMETRY_DISABLED = "1",
    DATABASE_URL = "",
    NEXTAUTH_SECRET = "",
    NEXTAUTH_URL = ""
  }

# Ensure contexts use Node 18.20.0
[context.production.environment]
  NODE_VERSION = "18.20.0"

[context.deploy-preview.environment]
  NODE_VERSION = "18.20.0"

[context.branch-deploy.environment]
  NODE_VERSION = "18.20.0"

# Functions configuration (Netlify Functions used by @netlify/plugin-nextjs)
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

# Redirects
# Route Netlify serverless functions for API endpoints (plugin usually handles this)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# Auth redirects commonly used by next-auth flows (adjust to your domain)
[[redirects]]
  from = "/api/auth/callback*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# Catch-all to ensure Next's server function handles other routes (plugin usually handles this)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = false

# Security & CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-store"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-XSS-Protection = "1; mode=block"

# Optional: control caching behaviour for improved rebuild times
[cache]
  paths = ["node_modules/**", ".next/cache/**"]

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# NOTES:
# - Set DATABASE_URL, NEXTAUTH_SECRET and NEXTAUTH_URL in Netlify site settings (Build & deploy -> Environment).
# - Netlify's Next plugin will automatically handle building and routing. These rules are safe fallbacks.
# - Avoid committing secrets to the repo. Use the Netlify UI or API to set secrets for production.
