[build]
  command = "npm run db:push -- --accept-data-loss && npm run db:seed && npx --yes @opennextjs/netlify build"
  publish = ".netlify/build"

[build.environment]
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
  NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "120000"
  NPM_CONFIG_NETWORK_TIMEOUT = "600000"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_PROGRESS = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
