[build]
  # If you rely on CI to run migrations/seeds, keep build simple.
  command = "pnpm build"

publish = ".next"

# Install dependencies without frozen-lockfile to allow CI to pick up package.json changes
command = "pnpm install --no-frozen-lockfile && pnpm build"

# If you prefer Netlify to run migrations and seed during build, change command to:
# command = "pnpm install --no-frozen-lockfile && pnpm db:generate && pnpm db:migrate && pnpm db:seed && pnpm build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  # Local dev settings if using netlify dev
  command = "pnpm dev"
  port = 3000
