[build]
  command = "pnpm db:generate && if [ -n \"$NETLIFY_DATABASE_URL\" ]; then export PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT=${PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT:-300000}; export NETLIFY_DATABASE_URL=${NETLIFY_DATABASE_URL_UNPOOLED:-$NETLIFY_DATABASE_URL}; pnpm tsx scripts/prisma-init-persistence.ts && bash ./scripts/prisma-deploy-retry.sh && pnpm db:seed; else echo 'Skipping Prisma migrate/seed (NETLIFY_DATABASE_URL not set)'; fi && pnpm test && pnpm lint && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "UPLOADS_PROVIDER,REALTIME_TRANSPORT"
  PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT = "300000"

[context.deploy-preview]
  command = "pnpm db:generate && echo 'Skipping Prisma migrate/seed in deploy-preview' && pnpm test && pnpm lint && pnpm build"

[context.branch-deploy]
  command = "pnpm db:generate && echo 'Skipping Prisma migrate/seed in branch-deploy' && pnpm test && pnpm lint && pnpm build"

[dev]
  command = "pnpm dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify/plugins/run-e2e"
