[build]
command = "npm run db:push && npm run db:seed && npm run build"
publish = ".next"

[build.environment]
DATABASE_URL = "${NETLIFY_DATABASE_URL}"

[[plugins]]
package = "@netlify/plugin-lighthouse"
