[build]
  command = "pnpm vercel:build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_FEATURE_UNIFIED_SETTINGS = "true"

[context.deploy-preview.environment]
  NEXT_PUBLIC_FEATURE_UNIFIED_SETTINGS = "false"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = false
