rules:
  - id: eval-usage
    pattern: eval(...)
    message: Avoid using eval() — it can lead to remote code execution.
    severity: ERROR
  - id: new-function-usage
    pattern: new Function(...)
    message: Avoid dynamic Function constructor — it can lead to remote code execution.
    severity: ERROR
  - id: dangerously-set-inner-html
    pattern: dangerouslySetInnerHTML: ...
    message: Avoid dangerouslySetInnerHTML unless content is sanitized.
    severity: WARNING
  - id: process-env-secret
    pattern: process.env[...]
    message: Ensure secrets from process.env are not logged or leaked and validated.
    severity: WARNING
  - id: require-dynamic
    pattern: require(...)
    message: Avoid dynamic require() where possible; prefer ES imports or add justified exceptions.
    severity: WARNING