[build]
  command = "cd next-app && npm ci && npm run build"
  publish = "next-app/.next"
  environment = { NODE_ENV = "production" }

[context.production.environment]
  # Set required environment variables in Netlify UI or via API
  # DATABASE_URL = "" 
  # NEXTAUTH_URL = "" 
  # NEXTAUTH_SECRET = "" 
  # NEXT_PUBLIC_API_BASE = "/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js for SSR and App Router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = false
