name: PR CI

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.16.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Run fast tests
        run: pnpm test:thresholds || true

  e2e:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.16.1 --activate

      - name: Install deps (with dev)
        run: pnpm install --frozen-lockfile

      - name: Run E2E (Playwright)
        env:
          CI: true
        run: pnpm e2e:ci || true
