name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
          run_install: false

      - name: Verify pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma generate
        if: ${{ env.DATABASE_URL != '' }}
        run: pnpm db:generate

      - name: Run Prisma migrations (deploy)
        if: ${{ env.DATABASE_URL != '' }}
        run: pnpm db:migrate

      - name: Seed database
        if: ${{ env.DATABASE_URL != '' }}
        run: pnpm db:seed

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run unit tests (thresholds)
        run: pnpm test:thresholds

      - name: Build Next.js
        run: pnpm build

      - name: Upload build artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
