name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CI: true
      PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT: "60000"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Show pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Run Prisma migrations (if DATABASE_URL is provided)
        if: ${{ env.DATABASE_URL != '' }}
        run: |
          pnpm db:migrate || pnpm exec prisma migrate resolve --applied 0002_add_tenant_columns || true
          pnpm db:migrate

      - name: Seed database (if DATABASE_URL is provided)
        if: ${{ env.DATABASE_URL != '' }}
        run: pnpm db:seed

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Unit tests (thresholds)
        run: pnpm test:thresholds

      - name: Build
        run: pnpm build
