name: CI

on:
  push:
    branches: [ main, ai_main_2843bb57fb55 ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Enable pnpm (corepack)
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Setup pnpm action (ensures pnpm in PATH)
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Typecheck (tsc + prisma generate)
        run: pnpm run typecheck

      - name: Run tests (vitest)
        env:
          CI: true
        run: pnpm exec vitest run --threads=false

      - name: Upload vitest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-results
          path: tests
