name: ClamAV Rescan

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  rescan:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-check secrets
        run: |
          if [ -z "${{ secrets.CRON_TARGET_URL }}" ] || [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "CRON secrets missing; skipping run." && exit 0
          fi
      - name: Trigger rescan endpoint
        run: |
          set -e
          curl -sS -X POST "${{ secrets.CRON_TARGET_URL }}/api/cron/rescan-attachments" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            -w "\nStatus: %{http_code}\n"
