name: Deploy to Netlify

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile

      - name: Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: pnpm build

      - name: Deploy to Netlify (requires NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID)
        if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli deploy --dir=.next --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

      - name: Skip deploy if no Netlify secrets
        if: ${{ !secrets.NETLIFY_AUTH_TOKEN || !secrets.NETLIFY_SITE_ID }}
        run: echo "NETLIFY_AUTH_TOKEN or NETLIFY_SITE_ID not set; skipping deploy."
