name: Netlify Preview Smoke

on:
  pull_request:

jobs:
  preview-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Wait for Netlify preview and run smoke test
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: node scripts/netlify-preview-smoke.js
