name: Playwright E2E

on:
  push:
    branches: [ glow-field ]
  pull_request:
    branches: [ glow-field ]

jobs:
  e2e:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build (skip env validation)
        run: pnpm run build:skip-env

      - name: Start production server
        run: |
          pnpm exec next start -p 3000 &
          echo "Waiting for server to be ready..."
          for i in {1..60}; do
            if curl -sSf http://localhost:3000 >/dev/null 2>&1; then
              echo "Server is up"
              break
            fi
            sleep 1
          done

      - name: Run Playwright tests
        run: pnpm exec playwright test e2e/tests/admin-sidebar.spec.ts -c e2e/playwright.config.ts --project=chromium --reporter=list
        env:
          E2E_BASE_URL: http://localhost:3000

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e-report
