name: Playwright E2E
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
      - name: Verify pnpm
        run: pnpm --version
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Build (skip env validation)
        run: pnpm build:skip-env
      - name: Start app
        run: |
          nohup pnpm exec next start -p 3000 > .next-start.log 2>&1 &
        env:
          NODE_ENV: production
          PORT: 3000
      - name: Wait for app
        run: |
          for i in {1..180}; do
            if curl -sSf http://localhost:3000 >/dev/null; then exit 0; fi
            sleep 1
          done
          echo "Server failed to start. Dumping logs:" && (tail -n +1 .next-start.log || true)
          exit 1
      - name: Run E2E tests
        env:
          E2E_BASE_URL: http://localhost:3000
        run: pnpm exec playwright test -c e2e/playwright.config.ts
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: e2e-report
