name: Rescan Attachments

on:
  schedule:
    - cron: '0 * * * *' # hourly
  workflow_dispatch: {}

jobs:
  rescan:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rescan endpoint
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$SITE_URL" ]; then echo "SITE_URL secret not set, skipping"; exit 0; fi
          curl -sSf -X POST "$SITE_URL/api/cron/rescan-attachments" -H "x-cron-secret: $CRON_SECRET" || true
